theme: jekyll-theme-minimal
title:  
description: Research Assistant and PhD Student at [DATEXIS](https://datexis.com) in Berlin
logo: https://github.com/bvanaken/bvanaken.github.io/raw/main/buddy_bear.png
