theme: jekyll-theme-minimal
title: <span></span>
description: Research Assistant and PhD Student at <href a="https://datexis.com" target="_blank">DATEXIS</a> in Berlin
logo: https://github.com/bvanaken/bvanaken.github.io/raw/main/buddy_bear.png
