theme: jekyll-theme-minimal
title: Betty van Aken
description: Research Assistant and PhD Student at DATEXIS in Berlin

[Send an email](mailto:bvanaken@beuth-hochschule.de)
logo: https://github.com/bvanaken/bvanaken.github.io/raw/main/buddy_bear.png
